name: Trigger Dependabot on Push

on:
  push:
    branches:
      - development # Specify the branches where you want to trigger Dependabot

jobs:
  trigger-dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Dependabot
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/dependabot/updates
